[project]
name = "si-integrations"
version = "0.1.0"
description = ""
requires-python = "==3.12.*"
dependencies = [
    "ipykernel>=7.2.0",
]
[dependency-groups]
dev = [
  "pytest",
  "pytest-cov",
  "ruff",
]
# Dependencies for integrations/earthmover notebooks and conversion scripts.
earthmover = [
  "azure-storage-blob",
  "azure-identity",
  "bokeh>=3.1.0",
  "matplotlib",
  "coiled",
  "dask[array]",
  "distributed",
  "icechunk",
  "ipykernel",
  "numpy",
  "pandas",
  "pyyaml",
  "rioxarray",
  "xarray",
  "odc-geo",
]
[tool.ruff]
target-version = "py312"
[tool.ruff.lint]
select = ["B", "E", "F", "I", "UP"]
[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]
"tests/**" = ["S"]
[tool.pytest.ini_options]
testpaths = ["tests"]
